export type KeySize = "large" | "medium" | "small" | "variable" | "custom";

export const AllKeys: {
  [key: string]: {
    displayValue: string;
    size: KeySize;
    className?: string;
  };
} = {
  KEY_GRAVE: { displayValue: "`", size: "variable" },
  KEY_1: { displayValue: "1", size: "variable" },
  KEY_2: { displayValue: "2", size: "variable" },
  KEY_3: { displayValue: "3", size: "variable" },
  KEY_4: { displayValue: "4", size: "variable" },
  KEY_5: { displayValue: "5", size: "variable" },
  KEY_6: { displayValue: "6", size: "variable" },
  KEY_7: { displayValue: "7", size: "variable" },
  KEY_8: { displayValue: "8", size: "variable" },
  KEY_9: { displayValue: "9", size: "variable" },
  KEY_0: { displayValue: "0", size: "variable" },
  KEY_MINUS: { displayValue: "-", size: "variable" },
  KEY_EQUAL: { displayValue: "=", size: "variable" },
  KEY_BACKSPACE: { displayValue: "Backspace", size: "medium" },
  KEY_TAB: { displayValue: "Tab", size: "small" },
  KEY_Q: { displayValue: "q", size: "variable" },
  KEY_W: { displayValue: "w", size: "variable" },
  KEY_E: { displayValue: "e", size: "variable" },
  KEY_R: { displayValue: "r", size: "variable" },
  KEY_T: { displayValue: "t", size: "variable" },
  KEY_Y: { displayValue: "y", size: "variable" },
  KEY_U: { displayValue: "u", size: "variable" },
  KEY_I: { displayValue: "i", size: "variable" },
  KEY_O: { displayValue: "o", size: "variable" },
  KEY_P: { displayValue: "p", size: "variable" },
  KEY_LEFTBRACE: { displayValue: "[", size: "variable" },
  KEY_RIGHTBRACE: { displayValue: "]", size: "variable" },
  KEY_BACKSLASH: { displayValue: "\\", size: "small" },
  KEY_CAPSLOCK: { displayValue: "CapsLock", size: "medium" },
  KEY_A: { displayValue: "a", size: "variable" },
  KEY_S: { displayValue: "s", size: "variable" },
  KEY_D: { displayValue: "d", size: "variable" },
  KEY_F: { displayValue: "f", size: "variable" },
  KEY_G: { displayValue: "g", size: "variable" },
  KEY_H: { displayValue: "h", size: "variable" },
  KEY_J: { displayValue: "j", size: "variable" },
  KEY_K: { displayValue: "k", size: "variable" },
  KEY_L: { displayValue: "l", size: "variable" },
  KEY_SEMICOLON: { displayValue: ";", size: "variable" },
  KEY_APOSTROPHE: { displayValue: "'", size: "variable" },
  KEY_ENTER: { displayValue: "Enter", size: "medium" },
  KEY_LEFTSHIFT: { displayValue: "LShift", size: "large" },
  KEY_Z: { displayValue: "z", size: "variable" },
  KEY_X: { displayValue: "x", size: "variable" },
  KEY_C: { displayValue: "c", size: "variable" },
  KEY_V: { displayValue: "v", size: "variable" },
  KEY_B: { displayValue: "b", size: "variable" },
  KEY_N: { displayValue: "n", size: "variable" },
  KEY_M: { displayValue: "m", size: "variable" },
  KEY_COMMA: { displayValue: ",", size: "variable" },
  KEY_DOT: { displayValue: ".", size: "variable" },
  KEY_SLASH: { displayValue: "/", size: "variable" },
  KEY_RIGHTSHIFT: { displayValue: "RShift", size: "large" },
  KEY_LEFTCTRL: { displayValue: "LCtrl", size: "variable" },
  KEY_LEFTALT: { displayValue: "LAlt", size: "variable" },
  KEY_SPACE: { displayValue: "Space", size: "custom", className: "w-[80%]" },
  KEY_RIGHTCTRL: { displayValue: "RAlt", size: "variable" },
  KEY_RIGHTALT: { displayValue: "RCtrl", size: "variable" },
};

export const querySortedRows: (keyof typeof AllKeys)[][] = [
  [
    "KEY_GRAVE",
    "KEY_1",
    "KEY_2",
    "KEY_3",
    "KEY_4",
    "KEY_5",
    "KEY_6",
    "KEY_7",
    "KEY_8",
    "KEY_9",
    "KEY_0",
    "KEY_MINUS",
    "KEY_EQUAL",
    "KEY_BACKSPACE",
  ],
  [
    "KEY_TAB",
    "KEY_Q",
    "KEY_W",
    "KEY_E",
    "KEY_R",
    "KEY_T",
    "KEY_Y",
    "KEY_U",
    "KEY_I",
    "KEY_O",
    "KEY_P",
    "KEY_LEFTBRACE",
    "KEY_RIGHTBRACE",
    "KEY_BACKSLASH",
  ],
  [
    "KEY_CAPSLOCK",
    "KEY_A",
    "KEY_S",
    "KEY_D",
    "KEY_F",
    "KEY_G",
    "KEY_H",
    "KEY_J",
    "KEY_K",
    "KEY_L",
    "KEY_SEMICOLON",
    "KEY_APOSTROPHE",
    "KEY_ENTER",
  ],
  [
    "KEY_LEFTSHIFT",
    "KEY_Z",
    "KEY_X",
    "KEY_C",
    "KEY_V",
    "KEY_B",
    "KEY_N",
    "KEY_M",
    "KEY_COMMA",
    "KEY_DOT",
    "KEY_SLASH",
    "KEY_RIGHTSHIFT",
  ],
  ["KEY_LEFTCTRL", "KEY_LEFTALT", "KEY_SPACE", "KEY_RIGHTALT", "KEY_RIGHTCTRL"],
];
